[package]
name = "generetta"
version = "0.1.0"
edition = "2021"
authors = ["kkharji <kkharji@proton.me>", "moaz-mokhtar <moaz.mokhtar@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
